`update` is now Termux-aware

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,28 +1,36 @@
 #!/bin/sh
 set -euf
 
-# should it be uncommented?
-#pkg upgrade # Termux
-
-# should I use apt-get?
-# "unstable API" doesn't seem to matter here
-if apt update && apt upgrade
-then
-	apt autoclean || true
-	apt autopurge || true
-
-	# https://github.com/pypa/pip/issues/4551
-
-	# if `apt` fails,
-	# it's likely `npm` will also fail
-	npm update -g || true # for LSPs
+if [ -z "${TERMUX_VERSION:-}" ]; then	
+	# should I use apt-get?
+	# "unstable API" doesn't seem to matter here
+	if apt update && apt upgrade
+	then
+		apt autoclean || true
+		apt autopurge || true
+	
+		# https://github.com/pypa/pip/issues/4551
+	
+		# if `apt` fails,
+		# it's likely `npm` will also fail
+		npm update -g || true # for LSPs
+	fi
+	
+	rustup upgrade
+	crates="$(\
+		cargo install --list |\
+		# assume stable Cargo API
+		grep -E '^[a-z0-9_-]+ v[0-9.]+:$' |\
+		cut -f1 -d' ' \
+	)"
+	[ -n "$crates" ] && cargo install $crates
+else
+	# https://wiki.termux.com/wiki/Package_Management
+	if pkg upgrade; then
+		# I have backups, no worries
+		pkg autoclean || true
+		apt autopurge || true
+	
+		npm update -g || true # for LSPs
+	fi
 fi
-
-rustup upgrade
-crates="$(\
-	cargo install --list |\
-	# assume stable Cargo API
-	grep -E '^[a-z0-9_-]+ v[0-9.]+:$' |\
-	cut -f1 -d' ' \
-)"
-[ -n "$crates" ] && cargo install $crates
